package mypackage;

import org.springframework.transaction.annotation.Transactional;
import java.util.Collection;

public interface ProductSuggestionRepository {

    // Get all product suggestions from the database.
    Collection<ProductSuggestion> getProductSuggestions();

    // Get the product suggestion with the specified ID.
    // Return null if there is no product with the specified ID.
    ProductSuggestion getProductSuggestion(long id);

    // Insert a new product suggestion into the database.
    // Return the ID generated by the database upon insertion.
    @Transactional
    long insertProductSuggestion(ProductSuggestion ps);

    // Modify the price of the specified product suggestion in the database.
    // Return true if successful, or false if there is no product with the specified ID.
    @Transactional
    boolean modifyPrice(long id, double newPrice);

    // Modify the expected sales of the specified product suggestion in the database.
    // Return true if successful, or false if there is no product with the specified ID.
    @Transactional
    boolean modifySales(long id, long newSales);

    // Delete all product suggestions from the database.
    @Transactional
    void deleteProductSuggestions();

    // Increase the price for all products that exceed a certain number of sales per year.
    @Transactional
    int increasePriceForPopularProducts(long sales);
}