FROM openjdk:17

ADD target/employee-app-0.0.1.jar app.jar

RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/myschema?serverTimezone=UTC > application.properties'
RUN sh -c 'echo spring.datasource.username=root    >> application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre >> application.properties'

ENTRYPOINT ["java","-jar","/app.jar"]
